# Generated by Django 3.1.7 on 2021-03-31 07:30

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_Name', models.CharField(max_length=300)),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_panel_1.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tut_priority', models.IntegerField(blank=True, null=True)),
                ('tut_title', models.CharField(max_length=200)),
                ('tut_body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('tut_views', models.IntegerField(default=0)),
                ('tut_timeDate', models.DateTimeField(auto_now_add=True)),
                ('topic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_panel_1.topic')),
            ],
        ),
    ]
