# Generated by Django 3.1.7 on 2021-03-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='sub_priority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='top_priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
