# Generated by Django 3.1.7 on 2021-03-31 14:05

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel_1', '0002_auto_20210331_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_priority', models.IntegerField(blank=True, null=True)),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_author', models.CharField(max_length=200)),
                ('blog_body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('blog_views', models.IntegerField(default=0)),
                ('blog_timeDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='topic',
            name='subject_name',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='topic_name',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
        migrations.AddField(
            model_name='blog',
            name='cat_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_panel_1.category'),
        ),
    ]
