# Generated by Django 3.1.7 on 2021-04-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel_1', '0009_auto_20210413_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_timeDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
