# Generated by Django 3.1.7 on 2021-04-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel_1', '0011_remove_blog_blog_thumbnil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_timeDate',
            new_name='blog_date',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
