# Generated by Django 3.1.7 on 2021-05-01 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel_1', '0012_auto_20210417_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_descriptions',
            field=models.CharField(default=django.utils.timezone.now, max_length=600),
            preserve_default=False,
        ),
    ]
