# Generated by Django 3.1.7 on 2021-05-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel_1', '0014_category_cat_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
