# Generated by Django 3.1.7 on 2021-05-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel_1', '0016_teammembers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='tm_priority',
            field=models.IntegerField(unique=True),
        ),
    ]
