# Generated by Django 3.1.7 on 2021-05-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel_1', '0017_auto_20210505_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='tm_bio',
            field=models.TextField(),
        ),
    ]
